@SurveyBasket.Api_HostAddress = https://localhost:7188

GET {{SurveyBasket.Api_HostAddress}}/api/polls/
Accept: application/json

###

@id=1
GET {{SurveyBasket.Api_HostAddress}}/api/polls/{{id}}

###
